server:
  port: ${SERVER_PORT}
jwt:
  secret: ${JWT_SECRET}
  access:
    lifetime: ${JWT_ACCESS_LIFE}
  refresh:
    lifetime: ${JWT_REFRESH_LIFE}
spring:
  application:
    name: AuthService
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}