server:
  port: ${SERVER_PORT}
spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    virtual-host: ${RABBIT_V_HOST}
    listener:
      simple:
        default-requeue-rejected: false
  application:
    name: NotificationService
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER_CONSUMER}
